FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o worker cmd/worker/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/worker .
RUN chmod +x worker

EXPOSE 8080

CMD ["./worker"]
